### PR TITLE
Fix 40 typos found by codespell

### PR DESCRIPTION
**Pull request by yarikoptic**
Here are typos with their counts and introduced fix:

      1 abritrary ==> arbitrary
      1 acccumulate ==> accumulate
      1 accidentaly ==> accidentally
      1 accordin ==> according
      1 acocunt ==> account
      1 additionaly ==> additionally
      1 adresses ==> addresses
      1 adviced ==> advised
      1 Algorithim ==> Algorithm
      1 alignement ==> alignment
      1 alogorithm ==> algorithm
      1 alogrithm ==> algorithm
      1 alowed ==> allowed
      1 analagous ==> analogous
      1 ananlysis ==> analysis
      1 appriopriate ==> appropriate
      1 appriximately ==> approximately
      1 appropiately ==> appropriately
      1 aproach ==> approach
      1 aproximation ==> approximation
      1 assesment ==> assessment
      1 Assingn ==> Assign
      1 assmptions ==> assumptions
      1 betwen ==> between
      1 beween ==> between
      1 bootstap ==> bootstrap
      1 bootstraping ==> bootstrapping
      1 boudary ==> boundary
      1 bounday ==> boundary
      1 caculate ==> calculate
      1 canoncial ==> canonical
     10 explicitely ==> explicitly
     11 emprical ==> empirical
     13 coeficients ==> coefficients
     15 detailled ==> detailed
     16 paramters ==> parameters
     17 accomodate ==> accommodate
     20 inital ==> initial
     21 usefull ==> useful
     25 occurences ==> occurrences

There are more but this was the first batch to swallow ;-)

### CODE REVIEW

**Comment by yarikoptic** [comment]
no interest whatsoever?

**Comment by ChristophePhillips** [comment]
Hi @yarikoptic 

Not quite sure who's in charge at the moment. As you know Guillaume "moved on" to other projects...
It looks like I could accept de merge but I would not act without SPM's manager, whoever it is, gives me the greenlight. 

Cheers,
Chris

**Comment by georgeoneill** [comment]
Hi @yarikoptic 

I'm also unsure what the official PR policy is yet.

HOWEVER... Can you exclude the `external` folder from you spellcheck please. Those subfolders are periodically synchronsed with 3rd party repositories so we have no control over the spelling in those files.

**Comment by pzeidman** [comment]
Hi @yarikoptic 
Thank you for making this pull request and to @ChristophePhillips and @georgeoneill for replying. Following the recent move to Github development, we have a temporary hold on accepting non-urgent PRs, while we review policy related to reviewing PRs, acknowledging contributors and software licensing. We expect to resume soon - thank you for your patience!

In the meantime @yarikoptic , as George mentioned - it would be great if you could re-issue your PR please without files in external dependencies (e.g., Fieldtrip).

Best
Peter (Chair, FIL Methods Group)

**Comment by yarikoptic** [comment]
Thanks for chiming back in! I should have mentioned that it was vendored inclusions! Unfortunately, probably I would just do not bother since exclusion was not yet provisioned in the helper I have used.  I might come back to it later, for now I will just let it RiP then. Cheers!

**Comment by pzeidman** [comment]
OK thanks @yarikoptic  - I will make the spelling corrections to the non-external files you highlighted and credit you in the commit message. Thanks for your time on this!

**Pull request closed without merging**
